package main;

import Utilerias.FondoImagen;
import controllers.Venta;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Producto;

/**
 *
 * @author echav
 */
public class MainFrame extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Venta venta = new Venta();
    int total = 0;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(6);
        modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        this.tblVenta.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        btnSencillo = new javax.swing.JButton();
        btnDoble = new javax.swing.JButton();
        btnCanasta = new javax.swing.JButton();
        btnCuarto = new javax.swing.JButton();
        btnMedio = new javax.swing.JButton();
        btnLitro = new javax.swing.JButton();
        btnPaletaChica = new javax.swing.JButton();
        btnPaletaGranda = new javax.swing.JButton();
        btnChamoyada = new javax.swing.JButton();
        btnAlpura = new javax.swing.JButton();
        btnDanonino = new javax.swing.JButton();
        btnCono = new javax.swing.JButton();
        pnlFirst = new javax.swing.JPanel();
        pnlLogo = new FondoImagen("logo.png");
        jLabel1 = new javax.swing.JLabel();
        pnlCuenta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        pnlBtnTerminarVenta = new javax.swing.JPanel();
        btnTerminarVenta = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        pnlVentaPersonalizada = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        pnlFondo.setBackground(new java.awt.Color(51, 51, 51));
        pnlFondo.setLayout(new java.awt.BorderLayout());

        pnlButtons.setBackground(new java.awt.Color(255, 189, 216));
        pnlButtons.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos para vender"));
        pnlButtons.setPreferredSize(new java.awt.Dimension(600, 500));
        pnlButtons.setLayout(new java.awt.GridLayout(4, 3));

        btnSencillo.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnSencillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heladoSencillo.png"))); // NOI18N
        btnSencillo.setText("Sencillo");
        btnSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSencilloActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSencillo);

        btnDoble.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnDoble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heladoDoble.png"))); // NOI18N
        btnDoble.setText("Doble");
        btnDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDobleActionPerformed(evt);
            }
        });
        pnlButtons.add(btnDoble);

        btnCanasta.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        btnCanasta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heladoCanasta.png"))); // NOI18N
        btnCanasta.setText("Canasta");
        btnCanasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanastaActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCanasta);

        btnCuarto.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnCuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heladoLitro.png"))); // NOI18N
        btnCuarto.setText("1/4");
        btnCuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuartoActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCuarto);

        btnMedio.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heladoLitro.png"))); // NOI18N
        btnMedio.setText("1/2");
        btnMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedioActionPerformed(evt);
            }
        });
        pnlButtons.add(btnMedio);

        btnLitro.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnLitro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heladoLitro.png"))); // NOI18N
        btnLitro.setText("1 Litro");
        btnLitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLitroActionPerformed(evt);
            }
        });
        pnlButtons.add(btnLitro);

        btnPaletaChica.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnPaletaChica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paletaChica.png"))); // NOI18N
        btnPaletaChica.setText("Chica");
        btnPaletaChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaletaChicaActionPerformed(evt);
            }
        });
        pnlButtons.add(btnPaletaChica);

        btnPaletaGranda.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnPaletaGranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paletaGrande.png"))); // NOI18N
        btnPaletaGranda.setText("Grande");
        btnPaletaGranda.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paletaGrande.png"))); // NOI18N
        btnPaletaGranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaletaGrandaActionPerformed(evt);
            }
        });
        pnlButtons.add(btnPaletaGranda);

        btnChamoyada.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnChamoyada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chamoyada.png"))); // NOI18N
        btnChamoyada.setText("Chamoyada");
        btnChamoyada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamoyadaActionPerformed(evt);
            }
        });
        pnlButtons.add(btnChamoyada);

        btnAlpura.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnAlpura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alpura.png"))); // NOI18N
        btnAlpura.setText("Alpura");
        btnAlpura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlpuraActionPerformed(evt);
            }
        });
        pnlButtons.add(btnAlpura);

        btnDanonino.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        btnDanonino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/danonino.png"))); // NOI18N
        btnDanonino.setText("Danonino");
        btnDanonino.setToolTipText("");
        btnDanonino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanoninoActionPerformed(evt);
            }
        });
        pnlButtons.add(btnDanonino);

        btnCono.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        btnCono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cono-de-helado.png"))); // NOI18N
        btnCono.setText("Conos");
        btnCono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConoActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCono);

        pnlFondo.add(pnlButtons, java.awt.BorderLayout.WEST);

        pnlFirst.setBackground(new java.awt.Color(255, 189, 216));
        pnlFirst.setLayout(new java.awt.BorderLayout());

        pnlLogo.setBackground(new java.awt.Color(204, 51, 255));
        pnlLogo.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlFirst.add(pnlLogo, java.awt.BorderLayout.WEST);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 33, 79));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paletería y Nevería");
        pnlFirst.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnlFondo.add(pnlFirst, java.awt.BorderLayout.PAGE_START);

        pnlCuenta.setBackground(new java.awt.Color(255, 189, 216));
        pnlCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuenta de la venta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlCuenta.setLayout(new java.awt.BorderLayout());

        tblVenta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblVenta.setRowHeight(24);
        jScrollPane2.setViewportView(tblVenta);

        pnlCuenta.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlBtnTerminarVenta.setBackground(new java.awt.Color(255, 189, 216));

        btnTerminarVenta.setBackground(new java.awt.Color(90, 187, 100));
        btnTerminarVenta.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        btnTerminarVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnTerminarVenta.setText("Terminar venta");
        btnTerminarVenta.setPreferredSize(new java.awt.Dimension(250, 100));
        btnTerminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarVentaActionPerformed(evt);
            }
        });
        pnlBtnTerminarVenta.add(btnTerminarVenta);

        lblTotal.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("Total: 0.00 MXN");
        pnlBtnTerminarVenta.add(lblTotal);

        pnlCuenta.add(pnlBtnTerminarVenta, java.awt.BorderLayout.PAGE_END);

        pnlVentaPersonalizada.setBackground(new java.awt.Color(255, 189, 216));
        pnlVentaPersonalizada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extras", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jButton14.setText("Agregar");

        javax.swing.GroupLayout pnlVentaPersonalizadaLayout = new javax.swing.GroupLayout(pnlVentaPersonalizada);
        pnlVentaPersonalizada.setLayout(pnlVentaPersonalizadaLayout);
        pnlVentaPersonalizadaLayout.setHorizontalGroup(
            pnlVentaPersonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentaPersonalizadaLayout.createSequentialGroup()
                .addGroup(pnlVentaPersonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVentaPersonalizadaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVentaPersonalizadaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pnlVentaPersonalizadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVentaPersonalizadaLayout.setVerticalGroup(
            pnlVentaPersonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentaPersonalizadaLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pnlCuenta.add(pnlVentaPersonalizada, java.awt.BorderLayout.LINE_END);

        pnlFondo.add(pnlCuenta, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlpuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlpuraActionPerformed
        this.crearFila(10);
    }//GEN-LAST:event_btnAlpuraActionPerformed

    private void btnSencilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSencilloActionPerformed
        this.crearFila(1);
    }//GEN-LAST:event_btnSencilloActionPerformed

    private void btnDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDobleActionPerformed
        this.crearFila(2);
    }//GEN-LAST:event_btnDobleActionPerformed

    private void btnCanastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanastaActionPerformed
        this.crearFila(3);
    }//GEN-LAST:event_btnCanastaActionPerformed

    private void btnCuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuartoActionPerformed
        this.crearFila(4);
    }//GEN-LAST:event_btnCuartoActionPerformed

    private void btnMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedioActionPerformed
        this.crearFila(5);
    }//GEN-LAST:event_btnMedioActionPerformed

    private void btnLitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLitroActionPerformed
        this.crearFila(6);
    }//GEN-LAST:event_btnLitroActionPerformed

    private void btnPaletaChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaletaChicaActionPerformed
        this.crearFila(7);
    }//GEN-LAST:event_btnPaletaChicaActionPerformed

    private void btnPaletaGrandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaletaGrandaActionPerformed
        this.crearFila(8);
    }//GEN-LAST:event_btnPaletaGrandaActionPerformed

    private void btnChamoyadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamoyadaActionPerformed
        this.crearFila(9);
    }//GEN-LAST:event_btnChamoyadaActionPerformed

    private void btnDanoninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanoninoActionPerformed
        this.crearFila(11);
    }//GEN-LAST:event_btnDanoninoActionPerformed

    private void btnConoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConoActionPerformed

    private void btnTerminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarVentaActionPerformed
        int fila = tblVenta.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        venta.guardarVenta();
        total = 0;
        this.lblTotal.setText("Total: " + total + ".00 MXN");
        JOptionPane.showMessageDialog(null, "Venta realizada con éxito");
    }//GEN-LAST:event_btnTerminarVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public void crearFila(int op) {
        Producto nuevo = new Producto();
        String fila[] = new String[3];
        switch (op) {
            case 1 -> {
                nuevo.setNombre("HELADO SENSILLO");
                nuevo.setPrecio(nuevo.PRECIO_HELADO_SENCILLO);
            }
            case 2 -> {
                nuevo.setNombre("HELADO DOBLE");
                nuevo.setPrecio(nuevo.PRECIO_HELADO_DOBLE);
            }
            case 3 -> {
                nuevo.setNombre("CANASTA");
                nuevo.setPrecio(nuevo.PRECIO_CANASTA);
            }
            case 4 -> {
                nuevo.setNombre("1/4 DE LITRO");
                nuevo.setPrecio(nuevo.PRECIO_CUARTO);
            }
            case 5 -> {
                nuevo.setNombre("1/2 LITRO");
                nuevo.setPrecio(nuevo.PRECIO_MEDIO);
            }
            case 6 -> {
                nuevo.setNombre("1 LITRO");
                nuevo.setPrecio(nuevo.PRECIO_LITRO);
            }
            case 7 -> {
                nuevo.setNombre("PALETA CHICA");
                nuevo.setPrecio(nuevo.PRECIO_PALETA_CHICA);
            }
            case 8 -> {
                nuevo.setNombre("PALETA GRANDE");
                nuevo.setPrecio(nuevo.PRECIO_PALETA_GRANDE);
            }
            case 9 -> {
                nuevo.setNombre("CHAMOYADA");
                nuevo.setPrecio(nuevo.PRECIO_CHAMOYADA);
            }
            case 10 -> {
                nuevo.setNombre("ALPURA");
                nuevo.setPrecio(nuevo.PRECIO_ALPURA);
            }
            case 11 -> {
                nuevo.setNombre("DANONINO");
                nuevo.setPrecio(nuevo.PRECIO_DANONINO);
            }
        }
        if (!venta.inVenta(nuevo.getNombre())) {
            nuevo.setCantidad(1);
            fila[0] = nuevo.getNombre();
            fila[1] = nuevo.getCantidad() + "";
            fila[2] = nuevo.getPrecio() + "";
            modelo.addRow(fila);
            venta.addProducto(nuevo);
            total += nuevo.getPrecio();
            this.lblTotal.setText("Total: " + total + ".00 MXN");
        } else {
            int renglon = venta.indexOf(nuevo.getNombre());
            Producto actual = (Producto) venta.getProductos().get(renglon);
            actual.setCantidad(actual.getCantidad() + 1);
            venta.getProductos().set(renglon, actual);
            modelo.setValueAt(actual.getCantidad() + "", renglon, 1);
            total += nuevo.getPrecio();
            this.lblTotal.setText("Total: " + total + ".00 MXN");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlpura;
    private javax.swing.JButton btnCanasta;
    private javax.swing.JButton btnChamoyada;
    private javax.swing.JButton btnCono;
    private javax.swing.JButton btnCuarto;
    private javax.swing.JButton btnDanonino;
    private javax.swing.JButton btnDoble;
    private javax.swing.JButton btnLitro;
    private javax.swing.JButton btnMedio;
    private javax.swing.JButton btnPaletaChica;
    private javax.swing.JButton btnPaletaGranda;
    private javax.swing.JButton btnSencillo;
    private javax.swing.JButton btnTerminarVenta;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBtnTerminarVenta;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCuenta;
    private javax.swing.JPanel pnlFirst;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlVentaPersonalizada;
    private javax.swing.JTable tblVenta;
    // End of variables declaration//GEN-END:variables
}
